# Generated by Django 4.2.18 on 2025-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fingerprint_image', models.ImageField(upload_to='fingerprints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
