# Generated by Django 4.2.18 on 2025-01-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person associated with the document.', max_length=255)),
                ('document_type', models.CharField(choices=[('CITIZENSHIP', 'Citizenship'), ('VOTER_ID', 'Voter ID'), ('LICENSE', 'License'), ('OTHER', 'Other')], help_text='Type of document being uploaded.', max_length=20)),
                ('document_file', models.FileField(help_text='Upload the document file.', upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
